# Generated by Django 4.2.5 on 2023-10-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_alter_carrera_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='carrera',
            new_name='carrera_id',
        ),
    ]
